networks:
    traefik_proxy_external:
        external: true
        name: "traefik_proxy_external"
services:
  api:
    build: .
    restart: unless-stopped
    env_file: .env.prod
    networks:
      - traefik_proxy_external
    depends_on:
      - mongo
    labels:
      - traefik.enable=true
      - traefik.http.routers.cafe-api.rule=Host(`cafe-api.jcool-laboratory-00.click`)
      - traefik.http.routers.cafe-api.entrypoints=web
      - traefik.http.services.cafe-api.loadbalancer.server.port=8000


  mongo:
    image: mongo:8
    restart: unless-stopped
    networks:
      - traefik_proxy_external
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: cafeteria_db
    volumes:
      - mongo_data:/data/db
    labels:
      - traefik.enable=true
      - traefik.http.routers.cafe-api.rule=Host(`cafe-api.jcool-laboratory-00.click`) && PathPrefix(`/mongo`)
      - traefik.http.routers.cafe-api.entrypoints=web
      - traefik.http.services.cafe-api.loadbalancer.server.port=27017

volumes:
  mongo_data:
