# Generated by Django 6.0.5 on 2026-05-11 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
